# Matrix Operations Tool

This project implements common matrix operations such as addition, subtraction,
multiplication, transpose, and determinant using Python and NumPy.


In [ ]:
import numpy as np


In [ ]:
def input_matrix(rows, cols):
    print(f"Enter values for a {rows}x{cols} matrix:")
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        matrix.append(row)
    return np.array(matrix)


In [ ]:
def show_menu():
    print("\nMATRIX OPERATIONS MENU")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Transpose")
    print("5. Determinant")
    print("6. Exit")


In [ ]:
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

A = input_matrix(rows, cols)
print("\nMatrix A:")
print(A)


Enter number of rows: 2
Enter number of columns: 3
Enter values for a 2x3 matrix:
Row 1: 0
Row 2: 2

Matrix A:
[[0.]
 [2.]]


In [ ]:
choice = int(input("Enter your choice: "))

if choice == 1:
    B = input_matrix(rows, cols)
    result = A + B
    print("Addition Result:\n", result)

elif choice == 2:
    B = input_matrix(rows, cols)
    result = A - B
    print("Subtraction Result:\n", result)


Enter your choice: 2
Enter values for a 2x3 matrix:
Row 1: 4
Row 2: 5
Subtraction Result:
 [[-4.]
 [-3.]]


In [ ]:
choice = int(input("Enter your choice: "))

if choice == 1:
    B = input_matrix(rows, cols)
    print("Addition Result:\n", A + B)

elif choice == 2:
    B = input_matrix(rows, cols)
    print("Subtraction Result:\n", A - B)

elif choice == 3:
    rows2 = int(input("Enter rows for Matrix B: "))
    cols2 = int(input("Enter columns for Matrix B: "))
    B = input_matrix(rows2, cols2)

    if cols != rows2:
        print("Matrix multiplication not possible!")
    else:
        result = np.dot(A, B)
        print("Multiplication Result:\n", result)

elif choice == 4:
    print("Transpose:\n", A.T)

elif choice == 5:
    if rows != cols:
        print("Determinant not possible!")
    else:
        print("Determinant:", np.linalg.det(A))

else:
    print("Invalid choice!")


Enter your choice: 2
Enter values for a 2x3 matrix:
Row 1: 3
Row 2: 2
Subtraction Result:
 [[-3.]
 [ 0.]]
